name: Deploy to Firebase

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        run: |
          node_version=$(node -e "console.log(require('./package.json').engines.node)")
          echo "Using Node.js version from package.json: $node_version"
          nvm use $node_version

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        run: |
          firebase use --token ${{ secrets.FIREBASE_TOKEN }}
          firebase use ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Build and Deploy
        run: |
          npm install
          npm run build 
          firebase deploy --only hosting
